apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dm-ingress 
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      # 配置Context Path。
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo-svc
            port:
              number: 80
