apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  annotations:
    kubernetes.io/change-cause: ${CHANGE_CAUSE}
  name: demo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: >-
            registry-vpc.cn-beijing.aliyuncs.com/dannyvi/warp-demo:5fe2869beb26ea7acec47287f6297105cc1756df
          imagePullPolicy: IfNotPresent
          name: demo
          ports:
            - containerPort: 8000
              name: api
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
