apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dm-ingress 
  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: alb
  tls:
  - hosts:
    - www.dannyvi.com
  rules:
    - host: www.dannyvi.com
      http:
        paths:
          - backend:
              service:
                name: demo-svc
                port:
                  number: 8000
            path: /*
            pathType: ImplementationSpecific
