
name: Build and Deploy Api End Point to Dev Environment

on:
  push:
    tags:
    - '*-dev-api'

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-beijing
  REGISTRY: registry.cn-beijing.aliyuncs.com
  NAMESPACE: dannyvi
  IMAGE: warp-demo
  ACK_CLUSTER_ID: c822e365aff4045f083ce0b40e9d858ac

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Add TAG env property with commit short sha
      run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
    
    # 1 Login to ACR   
    - name: Login to ACR with the AccessKey pair
      uses: aliyun/acr-login@v1
      with:
        region-id: "${{ env.REGION_ID }}"
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    # 2 Buid and push image to ACR   
    - name: Build and push image to ACR  
      run: |
        docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" .
        docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: production 
    
    # 3 Set ACK context         
    - name: Set K8s context
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}

    # 4 Deploy 
    - name: Deploy
      run: |
        sed -i "s|{{image}}|registry-vpc.cn-beijing.aliyuncs.com/dannyvi/warp-demo:$TAG|g" .k8/ask-deployment.yml
        kubectl apply -f .k8/ask-deployment.yml
  